// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/go-swagger/go-swagger/examples/tutorials/todo-list/cli/code/client/todos"

	"github.com/spf13/cobra"
)

// addOperationTodosDestroyOneCmd adds sub commands to operation opCmd
func addOperationTodosDestroyOneCmd(opCmd *cobra.Command) error {
	apiCmd := &cobra.Command{
		Use:   "destroyOne",
		Short: ``,
		RunE:  runOperationTodosDestroyOne,
	}

	if err := registerOperationTodosDestroyOneParamFlags(apiCmd); err != nil {
		return err
	}

	opCmd.AddCommand(apiCmd)

	return nil
}

// runOperationTodosDestroyOne uses cmd flags to call endpoint api
func runOperationTodosDestroyOne(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}

	params := todos.NewDestroyOneParams()
	// prepare params

	{
		// only set the param if user set the flag
		if cmd.Flags().Changed("id") {
			temp, err := cmd.Flags().GetInt64("id")
			if err != nil {
				return err
			}

			// set params
			params.ID = temp
		}

	}

	res, err := appCli.Todos.DestroyOne(params, nil)

	if err != nil {
		return err
	}

	// TODO: output payload properly, and handle error properly
	// output result
	log.Printf("%+v", res)
	msg, err := json.Marshal(res)
	if err == nil {
		fmt.Println(string(msg))
	}
	return nil
}

// registerOperationTodosDestroyOneParamFlags registers all flags needed to fill params
func registerOperationTodosDestroyOneParamFlags(cmd *cobra.Command) error {

	{
		// int64, default value is the zero value of the type.
		_ = cmd.PersistentFlags().Int64("id", 0, "Required. ")

		if err := cmd.MarkPersistentFlagRequired("id"); err != nil {
			return err
		}

	}

	return nil
}
