// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/examples/tutorials/todo-list/cli/code/models"
	"github.com/spf13/cobra"
)

// register flags to command
func addItemCmd(cmdPrefix string, cmd *cobra.Command) error {

	// property completed
	// TODO: not copy paste
	{
		cmdString := fmt.Sprintf("%vCompleted", cmdPrefix)
		_ = cmd.PersistentFlags().Bool(cmdString, false, "")

	}

	// property description
	// TODO: not copy paste
	{
		cmdString := fmt.Sprintf("%vDescription", cmdPrefix)
		_ = cmd.PersistentFlags().String(cmdString, "", "Required. ")

		if err := cmd.MarkPersistentFlagRequired(cmdString); err != nil {
			return err
		}

	}

	// property id
	// TODO: not copy paste
	{
		cmdString := fmt.Sprintf("%vID", cmdPrefix)
		_ = cmd.PersistentFlags().Int64(cmdString, 0, "")

	}

	return nil
}

// retrieve flags from commands, and set value in model . return true if user passed flag, i.e. field is added to model
func execItemCmd(m *models.Item, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	// property completed
	{
		cmdString := fmt.Sprintf("%vCompleted", cmdPrefix)
		if cmd.Flags().Changed(cmdString) { // only
			temp, err := cmd.Flags().GetBool(cmdString)
			if err != nil {
				return err, false
			}
			m.Completed = temp
			retAdded = true
		}
	}

	// property description
	{
		cmdString := fmt.Sprintf("%vDescription", cmdPrefix)
		if cmd.Flags().Changed(cmdString) { // only
			temp, err := cmd.Flags().GetString(cmdString)
			if err != nil {
				return err, false
			}
			m.Description = &temp
			retAdded = true
		}
	}

	// property id
	{
		cmdString := fmt.Sprintf("%vID", cmdPrefix)
		if cmd.Flags().Changed(cmdString) { // only
			temp, err := cmd.Flags().GetInt64(cmdString)
			if err != nil {
				return err, false
			}
			m.ID = temp
			retAdded = true
		}
	}

	return nil, retAdded
}
