// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/go-swagger/go-swagger/examples/tutorials/todo-list/cli/code/client/todos"
	"github.com/go-swagger/go-swagger/examples/tutorials/todo-list/cli/code/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// addOperationTodosUpdateOneCmd adds sub commands to operation opCmd
func addOperationTodosUpdateOneCmd(opCmd *cobra.Command) error {
	apiCmd := &cobra.Command{
		Use:   "updateOne",
		Short: ``,
		RunE:  runOperationTodosUpdateOne,
	}

	if err := registerOperationTodosUpdateOneParamFlags(apiCmd); err != nil {
		return err
	}

	opCmd.AddCommand(apiCmd)

	return nil
}

// runOperationTodosUpdateOne uses cmd flags to call endpoint api
func runOperationTodosUpdateOne(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}

	params := todos.NewUpdateOneParams()
	// prepare params

	{
		// only set the param if user set the flag
		if cmd.Flags().Changed("body") {
			// struct Body. Read the string from cmd and unmarshal
			tempStr, err := cmd.Flags().GetString("body")
			if err != nil {
				return err
			}
			temp := models.Item{}
			if err := temp.UnmarshalBinary([]byte(tempStr)); err != nil {
				return err
			}
			fmt.Printf("body is set unmarshal")

			// set params
			params.Body = &temp
		}
		// recurse on model
		tempModel := params.Body
		if swag.IsZero(tempModel) {
			tempModel = &models.Item{}
		}
		err, added := retrieveItemFlags(tempModel, "item", cmd)
		if err != nil {
			return err
		}
		if added {
			params.Body = tempModel
		}

	}
	{
		// only set the param if user set the flag
		if cmd.Flags().Changed("id") {
			temp, err := cmd.Flags().GetInt64("id")
			if err != nil {
				return err
			}

			// set params
			params.ID = temp
		}

	}

	res, err := appCli.Todos.UpdateOne(params, nil)

	if err != nil {
		return err
	}

	// TODO: output payload properly, and handle error properly
	// output result
	log.Printf("%+v", res)
	msg, err := json.Marshal(res)
	if err == nil {
		fmt.Println(string(msg))
	}
	return nil
}

// registerOperationTodosUpdateOneParamFlags registers all flags needed to fill params
func registerOperationTodosUpdateOneParamFlags(cmd *cobra.Command) error {

	{
		// models.Item, default value is the zero value of the type.
		// struct Body. Read the string from cmd and unmarshal
		temp := &models.Item{}
		exampleStr, err := temp.MarshalBinary()
		if err != nil {
			return err
		}
		// TODO: give better example str
		_ = cmd.PersistentFlags().String("body", "", fmt.Sprintf("Optional json string for body of form %v.", string(exampleStr)))

		// add flags for body
		addItemCmd("item", cmd)
	}

	{
		// int64, default value is the zero value of the type.
		_ = cmd.PersistentFlags().Int64("id", 0, "Required. ")

		if err := cmd.MarkPersistentFlagRequired("id"); err != nil {
			return err
		}

	}

	return nil
}
