// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"encoding/json"
	"log"
	"os"

	"github.com/go-swagger/go-swagger/examples/tutorials/todo-list/cli/code/cli"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

func main() {
	rootCmd := cli.MakeRootCmd()
	if err := rootCmd.Execute(); err != nil {
		log.Print("Error:", err)
		// print the whole struct as json if possible
		msg, jErr := json.Marshal(err)
		if jErr == nil {
			log.Print("ErrorJson:", string(msg))
		}
		os.Exit(1)
	}
}
